// Generated by FlutterFire CLI — Maternify project: maternify-91c75
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmslMb2e0rw9ZAYm8kcQXN2wP28EW7tVU',
    appId: '1:1045513431035:web:d2b900b98ab8d027808d5e',
    messagingSenderId: '1045513431035',
    projectId: 'maternify-91c75',
    authDomain: 'maternify-91c75.firebaseapp.com',
    storageBucket: 'maternify-91c75.firebasestorage.app',
    measurementId: 'G-RK3KZVRXSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp1CCA9lOt43PkPADHrNEYHCcLcJkbyC0',
    appId: '1:1045513431035:android:4d0cddf3675d8e49808d5e',
    messagingSenderId: '1045513431035',
    projectId: 'maternify-91c75',
    storageBucket: 'maternify-91c75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmslMb2e0rw9ZAYm8kcQXN2wP28EW7tVU',
    appId: '1:1045513431035:ios:0000000000000000808d5e',
    messagingSenderId: '1045513431035',
    projectId: 'maternify-91c75',
    storageBucket: 'maternify-91c75.firebasestorage.app',
    iosBundleId: 'com.maternify.app',
  );
}
