// Generated by FlutterFire CLI — replace with real values from Firebase Console.
// For hackathon demo: these placeholders allow the app to boot without crashing.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  // ── Replace all values below with your real Firebase project config ──────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-replace-with-real-key',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'maternify-demo',
    authDomain: 'maternify-demo.firebaseapp.com',
    storageBucket: 'maternify-demo.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-replace-with-real-key',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'maternify-demo',
    storageBucket: 'maternify-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-replace-with-real-key',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'maternify-demo',
    storageBucket: 'maternify-demo.appspot.com',
    iosBundleId: 'com.maternify.app',
  );
}
